volumes:
    postgres-data:
        external: true
    pg-admin:
        external: true
services:
  accounts:
    build:
      context: accounts_api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./accounts_api:/app
    environment:
      DATABASE_URL: postgresql://accounts:password@postgres/accounts
      SIGNING_KEY: 87fe4a3fcfb60092dbaeb854a196bc3d9b190aed7930c734749e85245de698420c25f8e6899c421b4494e99459e01058de5daa9d49584cd62ec975da9aea33da
      WAIT_HOSTS: postgres:5432

  events:
    build:
      context: events_api
      dockerfile: Dockerfile.dev
    ports:
      - 8001:8000
    volumes:
      - ./events_api:/app
    environment:
      DATABASE_URL: postgresql://events:password@postgres/events
      SIGNING_KEY: 87fe4a3fcfb60092dbaeb854a196bc3d9b190aed7930c734749e85245de698420c25f8e6899c421b4494e99459e01058de5daa9d49584cd62ec975da9aea33da
      WAIT_HOSTS: postgres:5432
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60


  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_ACCOUNT_SERVICE: http://localhost:8000

  postgres:
    build:
      context: ./relational-data
      dockerfile: ./Dockerfile.dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_MULTIPLE_DATABASES=accounts,events
      - POSTGRES_PASSWORD=test-databases
    ports:
      - 15432:5432

  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@email.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_DISABLE_POSTFIX: 1
