volumes:
    postgres-data:
        external: true
services:
  accounts:
    build:
      context: accounts_api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./accounts_api:/app
    environment:
      DATABASE_URL: postgresql://accounts:password@postgres/accounts
      WAIT_HOSTS: postgres:5432

  events:
    build:
      context: events_api
      dockerfile: Dockerfile.dev
    ports:
      - 8001:8000
    volumes:
      - ./events_api:/app
    environment:
      DATABASE_URL: postgresql://events:password@postgres/events
      WAIT_HOSTS: postgres:5432

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_SAMPLE_SERVICE_API_HOST: http://localhost:8000

  postgres:
    build:
      context: ./relational-data
      dockerfile: ./Dockerfile.dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_MULTIPLE_DATABASES=accounts,events
      - POSTGRES_PASSWORD=test-databases
    ports:
      - 15432:5432
